runs:
  using: "composite"
  steps:
    - name: Update
      run: sudo apt update
      shell: bash

    - name: Install c++ libs
      run: |
        sudo apt install libxerces-c-dev -y
        sudo apt install build-essential libboost-system-dev libboost-thread-dev libboost-program-options-dev libboost-test-dev -y
      shell: bash
