runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install libxerces-c-dev -y
        sudo apt install cmake -y
        sudo apt install libboost-program-options-dev -y
