name: "🚀 Feature request"
description: Suggest a new feature or improvement.
labels: [feature]
body:
  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
      description: Please describe. A clear and concise description of what the problem is.
      placeholder: Ex. I'm always frustrated when ...
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: Describe the solution you'd like
    validations:
      required: true
