name: Build and Test

on:
  pull_request:
    paths:
      - "src/**"
      - "**CMakeLists.txt"
      - ".github/workflows/build-project-test-project.yml"
      - ".github/actions/install-dependencies/**"
  push:
    branches: "master"
    paths:
      - "src/**"
      - "**CMakeLists.txt"
      - ".github/workflows/build-project-test-project.yml"
      - ".github/actions/install-dependencies/**"
  workflow_dispatch:

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/install-dependencies

      - name: Run CMake
        run: |
          rm -rf build
          mkdir build
          cd build
          cmake -DCMAKE_CXX_FLAGS="-Werror -Wall" ..

      - name: Build project
        run: |
          cd build
          make -j

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |
            build/tests
            build/project
          retention-days: 1

  execute-unit-tests:
    needs: build-project
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: build/

      - name: Execute Tests
        run: |
          cd build/tests
          chmod +x ./tests
          ./tests
