name: Build and Test

on:
  pull_request:
    paths:
      - "src/**"
      - "**CMakeLists.txt"
      - ".github/workflows/build-project-test-project.yml"
  push:
    branches: "master"
    paths:
      - "src/**"
      - "**CMakeLists.txt"
      - ".github/workflows/build-project-test-project.yml"
  workflow_dispatch:

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          sudo apt update
          sudo apt install libxerces-c-dev -y
          sudo apt install cmake -y
          sudo apt-get install libboost-program-options-dev -y

      - name: Run CMake
        run: |
          rm -rf build
          mkdir build
          cd build
          cmake -DCMAKE_CXX_FLAGS="-Werror -Wall" ..

      - name: Build project
        run: |
          cd build
          make -j

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |
            build/tests
            build/project
          retention-days: 1

  execute-unit-tests:
    needs: build-project
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: build/tests

      - name: Execute Tests
        run: |
          cd build/tests
          chmod +x ./tests
          ./tests

  analyze:
    needs: build-project
    name: Analyze
    runs-on: "ubuntu-latest"
    timeout-minutes: 360
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ["c-cpp"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: build/project

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"
