name: Build Backend

on:
  pull_request:
    branches: "*"
    types:
      - labeled
      - synchronize
  workflow_dispatch:

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install libxerces-c-dev
        run: |
          sudo apt update
          sudo apt install libxerces-c-dev -y
          sudo apt install cmake -y

      - name: Run CMake
        run: |
          rm -rf build
          mkdir build
          cd build
          cmake -DCMAKE_CXX_FLAGS="-Werror -Wall -Wextra" ..

      - name: Build project
        run: |
          cd build
          make
