name: Build Project

on:
  pull_request:
    paths:
      - "src/**"
      - "**CMakeLists.txt"
      - ".github/workflows/build.yml"
  push:
    branches: "master"
    paths:
      - "src/**"
      - "**CMakeLists.txt"
      - ".github/workflows/build.yml"
  workflow_dispatch:

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          sudo apt update
          sudo apt install libxerces-c-dev -y
          sudo apt install cmake -y
          sudo apt-get install libboost-program-options-dev -y

      - name: Run CMake
        run: |
          rm -rf build
          mkdir build
          cd build
          cmake -DCMAKE_CXX_FLAGS="-Werror -Wall" ..

      - name: Build project
        run: |
          cd build
          make -j
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build/tests
          retention-days: 1

  execute-unit-tests:
    needs: build-project
    runs-on: ubuntu-latest
    
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: build/tests

      - name: Execute Tests
        run: |
          cd build/tests
          chmod +x ./tests
          ./tests