name: Issue Opened
on:
  issues:
    types: [opened]

jobs:
  addToProject:
    runs-on: ubuntu-latest
    steps:
      - name: Add Issue to Project
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: MolSim-WS23-24
          column: Todo
          repo-token: ${{ secrets.GITHUB_TOKEN }}
