name: Project automation

on:
  pull_request:
    types:
      - opened
      - reopened
      - review_requested
      - closed

jobs:
  pr_opened_or_reopened_or_reviewrequested:
    name: pr_opened_or_reopened_or_reviewrequested
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'review_requested')
    steps:
      - name: Move PR to in Progress
        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          user: ManuelLerchner
          project_id: 4
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: In Progress
