name: Check Submissions

on:
  push:
    branches:
      - presentations

  workflow_dispatch:

jobs:
  check-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Check for all sheet[num] folders if they contain a submission folder
      # Each submission folder should contain atleast a `GroupC_Assignment[num].pdf` and `README.md` file
      - name: Check Submissions
        run: |
          for i in $(find . -type d -name "sheet*"); do
          if [ -d "$i/submission" ]; then
              if [ ! $(find $i/submission -type f -name "README.md" | wc -l) -eq 1 ]; then
                  echo "Missing README.md in $i/submission"
                  exit 1
              fi
              if [ ! $(find $i/submission -type f -name "GroupC_Assignment*.pdf" | wc -l) -eq 1 ]; then
                  echo "Missing GroupC_Assignment*.pdf in $i/submission"
                  exit 1
              fi
          fi
          done

      - name: Check for <TODO> Markers in sheetXX folders
        run: |
          # Search for <TODO> markers only within sheetXX folder
          TODO_COUNT=$(grep -r "<TODO>" sheet* | wc -l)
          if [ $TODO_COUNT -gt 0 ]; then
              echo "There are $TODO_COUNT <TODO> markers left in the sheetXX folders."
              echo "Please remove them before submitting."
              echo -n "$(grep -r "<TODO>" sheet*)"
              exit 0
          fi
